// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6X6L-XMLx9JDvEkuTJkKlCIfq6Wx_XgI',
    appId: '1:465540732800:web:075e5432fed35754bf9365',
    messagingSenderId: '465540732800',
    projectId: 'flutterprojet-e8896',
    authDomain: 'flutterprojet-e8896.firebaseapp.com',
    storageBucket: 'flutterprojet-e8896.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEYvBih0Eelwl1cyQRsPYo3fDLHTaB1dY',
    appId: '1:465540732800:android:6f03d19d73367d63bf9365',
    messagingSenderId: '465540732800',
    projectId: 'flutterprojet-e8896',
    storageBucket: 'flutterprojet-e8896.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDtXJjVR8ubcBVvdPJENeOsxkn-RWic1g',
    appId: '1:465540732800:ios:679fc74133151889bf9365',
    messagingSenderId: '465540732800',
    projectId: 'flutterprojet-e8896',
    storageBucket: 'flutterprojet-e8896.appspot.com',
    androidClientId: '465540732800-09qhrlad1t0tet50ohgr01g8tdqkc30l.apps.googleusercontent.com',
    iosClientId: '465540732800-9h6m99rfjlsvebdk2j6ur8dp2vk4hvme.apps.googleusercontent.com',
    iosBundleId: 'com.example.smatchManagment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDtXJjVR8ubcBVvdPJENeOsxkn-RWic1g',
    appId: '1:465540732800:ios:679fc74133151889bf9365',
    messagingSenderId: '465540732800',
    projectId: 'flutterprojet-e8896',
    storageBucket: 'flutterprojet-e8896.appspot.com',
    androidClientId: '465540732800-09qhrlad1t0tet50ohgr01g8tdqkc30l.apps.googleusercontent.com',
    iosClientId: '465540732800-9h6m99rfjlsvebdk2j6ur8dp2vk4hvme.apps.googleusercontent.com',
    iosBundleId: 'com.example.smatchManagment',
  );
}
